<script type="text/javascript" src="<?php echo $block->getViewFileUrl('Bluedart_Shipment::js/jquery.validate.min.js'); ?>"></script>
<script type="text/javascript">
jQuery.noConflict();
 jQuery(document).ready(function() {
  jQuery("#waybillcancelation").validate({
      rules: {
        waybillnumber: {required : true,number: true, /*maxlength: 12, minlength: 12*/},
      },      
    });
});
jQuery.validator.setDefaults({
    submitHandler: function() {
    	jQuery('#ajax-loader').show();
        jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->getUrl('shipment/index/Waybillcancelationvalidate'); ?>",
                data: { 'waybillnumber' : jQuery('#waybillnumber').val() },
                success: function(data){
                if(data != ''){
                    jQuery('#ajax-loader').hide();
                    jQuery('#waybillvalidmessage').html(data);
                }
            }
        });
    }
  });
  function resetForm() {
    jQuery('#waybillvalidmessage').html('');
    jQuery("#waybillcancelation").validate().resetForm();
  }

   </script>
<form  name="waybillcancelation" id = "waybillcancelation" novalidate="novalidate">
<div class="pincode">
<h3>Waybill Cancellation :</h3>
<span>Waybill Number <span class="required">*</span></span>:&nbsp;&nbsp;<input type="text" maxlength="13" size="13" id="waybillnumber" name="waybillnumber"></input><br/>
<button class="go_button1" type="submit">Cancel Awb</button>
<button class="go_button" type="button" onclick="reset();resetForm();">Reset</button><br/>
<div id="ajax-loader" style="display:none;margin:2% 0 0 15%;">
  <img src="<?php echo $this->getViewFileUrl('Bluedart_Shipment::images/ajax-loader.gif'); ?>">
</div>
<div id="waybillvalidmessage" class="waybillvalidmessage"></div>
</form>
   <style type="text/css">
    .divTable
    {
        display:  table;
        width:auto;
        background-color:#eee;
        border:1px solid  #666666;
        border-spacing:5px;margin:10px 0 0;/*cellspacing:poor IE support for  this*/
       /* border-collapse:separate;*/
       width: 50%;
    }
    .divRow
    {
       display:table-row;
       width:auto;
    }
  .divCell
  {
        float:left;/*fix for  buggy browsers*/
        display:table-column;
        background-color:#ccc;
  }
  .pincode, .pincodes{width: 100%;}
  .pincode span,.pincodes p span{
    width:12%;
    float:left;
    display:block;
    margin:5px 10px 0px 0;
    text-align:right;
  }
  .pincodes p{overflow: auto;margin: 0;padding: 0 5px;}
  .pincodes p span{width:50%;
    text-align:left;
    margin:5px 0;
  }
  .pincode input{margin: 5px 0;}
  .pincode .go_button{margin: 0 0 0 7.8%;}
  .pincodes p:nth-child(odd) {
    background: #FEFEFE;}
  .pincodes p:nth-child(even) {
    background: #CDE0F1;}

  .pincode span .required{color:#F00;float:right;margin:0 0 0 2px;font-weight: bold;}
  .pincodes p:first-child {
    background: #0F6FC6;color: #fff;}
  .pincode .go_button1{margin: 0 0 0 9.4%;}
  .pincode .go_button{margin: 0 0 0 1%;}
  .pincodes span.error_msg{font-weight: bold;color: #D40707;}
</style>
