<?php
    /**
    * Copyright © 2015 Magento. All rights reserved.
    * See COPYING.txt for license details.
    */

    // @codingStandardsIgnoreFile

?>
<div class="footer-container footer-type1">
    <div class="footer">

        <div class="footer-top-outer">
            <div class="footer-top-inner container container-width">
                <div class="col-lg-12  col-md-12  col-sm-12  col-xs-12">
                    <div class="row">
                        <div class="footer-top-section1 footer-top-section">
                            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_top_block1')->toHtml();?>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="footer-middle-outer">
            <div class="footer-middle-inner container container-width">
                <div class="row">
                    <div class="col-lg-12  col-md-12  col-sm-12  col-xs-12">
                        <div class="row">
                            <div class="footer-middle-section1 footer-middle-section col-xs-12 col-sm-12 col-md-3 col-lg-4">
                                <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_middle_section1')->toHtml();?>
                            </div>
                            <div class="footer-middle-section2 footer-middle-section col-xs-12 col-sm-12 col-md-3 col-lg-4">
                                <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_middle_section2')->toHtml();?>
                            </div>
                            <div class="footer-middle-section3 footer-middle-section col-xs-12 col-sm-12 col-md-3 col-lg-4">
                                <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_middle_section3')->toHtml();?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="footer-bottom-outer">
            <div class="footer-bottom-inner container container-width">
                <div class="row">
                    <div class="col-lg-12  col-md-12  col-sm-12  col-xs-12">
                        <div class="footer-bottom-section">
                            <div class="bottom_copyright">	
                                <?php echo $block->getChildHtml('footer_links') ?>
                                <?php echo $block->getChildHtml('copyright'); ?>
                                <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_payment')->toHtml();?>
                            </div>
                        </div>	
                    </div>
                </div>
            </div>
        </div>

        <?php /*?> <?php echo $block->getChildHtml() ?><?php */?>


    </div>
</div>



<?php /*?><div class="footer-container">
    <div class="footer">

    <div class="footer-top-outer">
    <div class="footer-top-inner container-width">
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_top')->toHtml();?>
    </div>
    </div>

    <div class="footer-middle-outer">
    <div class="footer-middle-inner container-width">
    <div class="footer-middle-section1 footer-middle-section col-xs-12 col-sm-12 col-md-3 col-lg-3">
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_middle_section1')->toHtml();?>
    </div>
    <div class="footer-middle-section2 footer-middle-section col-xs-12 col-sm-12 col-md-3 col-lg-3">
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_middle_section2')->toHtml();?>
    </div>
    <div class="footer-middle-section3 footer-middle-section col-xs-12 col-sm-12 col-md-3 col-lg-3">
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_middle_section3')->toHtml();?>
    </div>
    <div class="footer-middle-section4 footer-middle-section col-xs-12 col-sm-12 col-md-3 col-lg-3">
    <?php echo $block->getChildHtml('newsletter.subscribe') ?>
    </div>
    </div>
    </div>

    <div class="footer-bottom-outer">
    <div class="footer-bottom-inner container-width">
    <div class="footer-bottom-section1 footer-bottom-section">
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_bottom_social')->toHtml();?>
    </div>
    <div class="footer-bottom-section2 footer-bottom-section">
    <div class="bottom_copyright">
    <?php echo $block->getChildHtml('copyright'); ?>
    <?php echo $block->getChildHtml('footer_links') ?>
    </div>
    </div>
    <div class="footer-bottom-section3 footer-bottom-section">
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_bottom_payment')->toHtml();?>
    </div>		
    </div>
    </div>

    <?php echo $block->getChildHtml() ?> ?>


    </div>
    </div>
<?php */?>