

<div class="header content">
		<?php echo $this->getChildHtml("logo"); ?>
		
		<div class="header_right_outer">
			<div class="haeder_left">
				<?php echo $this->getChildHtml("navigation.sections"); ?>
			</div>
			<div class="header_right">
				
				<div class="header_cart">
						<?php echo $this->getChildHtml("minicart"); ?>
				 </div>
				 
				<div class="header_menu_dropdown">
						<div class="haeder_icon">
								<div class="haeder_icon_image">&nbsp;</div>
						</div>
						<div class="header_toggle_menu">
							<?php echo $this->getChildHtml("skip_to_content"); ?>
							<?php echo $this->getChildHtml("header.links"); ?>
							<?php echo $this->getChildHtml("store_language"); ?>
							<?php echo $this->getChildHtml("currency"); ?>	
						</div>
				</div>
				<div class="header_search">
						<div class="haeder_search_image">&nbsp;</div>
						<div class="header_search_toggle">
							<?php echo $this->getChildHtml("top.search"); ?>
						</div>
				</div>		
				
			</div>
		</div>
		
			
		
</div>







