<!--
/**
 * Purpletree_Rma return_orders_button_content
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Purpletree License that is bundled with this package in the file license.txt.
 * It is also available through online at this URL: https://www.purpletreesoftware.com/license.html
 *
 * @category    Purpletree
 * @package     Purpletree_Rma
 * @author      Purpletree Software
 * @copyright   Copyright (c) 2017
 * @license     https://www.purpletreesoftware.com/license.html
 */
-->
<td style="display:none" class="returntd">
<?php
$objectManager  = \Magento\Framework\App\ObjectManager::getInstance();
$data_helper 	= $objectManager->create('Purpletree\Rma\Helper\Data');
$isEnabled 		= $data_helper->isEnabled();
	if($isEnabled) {
		$order 		= $block->getOrder();
		$_orderreturn   = $objectManager->create('Purpletree\Rma\Model\ResourceModel\Orderreturn');
		$entityId = $_orderreturn->getOrderreturnIdByOrderId($order->getRealOrderId());
			if(!$entityId) {
				if($order->getState() == 'complete') {
					$statusHistoryItem = $order->getStatusHistoryCollection()->getFirstItem();
					 $status_date 	   = $statusHistoryItem->getCreatedAt();
					 if($status_date == '') {
						  foreach($order->getShipmentsCollection() as $shipment){
								/** @var $shipment Mage_Sales_Model_Order_Shipment */
							$status_date = $shipment->getCreatedAt();
						  }
					  }
					 $datee 		   = $objectManager->create('\Magento\Framework\Stdlib\DateTime\DateTime');
					 $time_frame 	   = $data_helper->getGeneralConfig('/general/day_completion');
					 $effectiveDate     = strtotime("+ " . $time_frame . ' days', strtotime($status_date)); //returns timestamp
					 $effectiveDate  =  date('Y-m-d H:i:s', $effectiveDate); // formatted version
						if ($datee->date() < $datee->date($effectiveDate)) { ?>
						<a id="<?php echo $order->getId(); ?>"  href="<?php echo $this->getUrl('rma/index/initiate', ['order_id' => $order->getId()]); ?>" class="action view returnbutton">
							<span><?php echo __('Return') ?></span>
						</a>
				<?php } } } else { ?>
						<a id="<?php echo $order->getId(); ?>" href="<?php echo $this->getUrl('rma/index/view', ['id' => $entityId]); ?>" class="returnbutton action view">
							<span><?php echo __('Return Status') ?></span>
						</a>
	<?php } } ?>
	 <script type="text/javascript">
require(['jquery'], function($) {
	$(document).ready(function($) {
		$(".returnbutton").each(function(){
			wrapper = $(this).parent().parent().children('.col.actions');
			$(this).detach().appendTo(wrapper);
		});
	})
})
</script>
	</td>