<!--
/**
 * Purpletree_Rma terms
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Purpletree License that is bundled with this package in the file license.txt.
 * It is also available through online at this URL: https://www.purpletreesoftware.com/license.html
 *
 * @category    Purpletree
 * @package     Purpletree_Rma
 * @author      Purpletree Software
 * @copyright   Copyright (c) 2017
 * @license     https://www.purpletreesoftware.com/license.html
 */
-->
<?php 
$objectManager  = \Magento\Framework\App\ObjectManager::getInstance();
$data_helper 	= $objectManager->create('Purpletree\Rma\Helper\Data');

echo $data_helper->getGeneralConfig('/general/terms');

?>