<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_newhelper = $this->helper('Ortho\Newproduct\Helper\Data');
$modulestatus = $_newhelper->getNewstatus();
if($modulestatus){
?>
<?php
$_productCollection = $block->getNewProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');


?>
<div class="home-newproduct common-slider-outer">
<div class="content-heading">
			<h2 class="title"><?php echo $_newhelper->getNewTitle();  ?></h2>
	</div>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>

    <?php
  
        $viewMode = 'grid';
        $image = 'homepage_product_carousel';
		$hoverimage = 'homepage_product_hover_carousel';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
	
	
    <div class="products common-slider grid-hover newproduct wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items new-slider owl-carousel">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="owl-item product product-item" style="width:100%;">' : '</li><li class="owl-item product product-item" style="width:100%;">' ?>
                <div class="product-item-info" data-container="product-carousel">
                    <?php
                    $productImage = $block->getImage($_product, $image);
					$producthoverImage = $block->getImage($_product, $hoverimage);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
					  <div class="product-grid-image">
							<?php
							$productlabel = $this->helper('Ortho\Theme\Helper\Data');
							if($productlabel->getSaleLabel($_product)){
							?>
								<div class="sale-label"><span><?php /* @escapeNotVerified */ echo __('Sale') ?></div>
							<?php
							}
						    if($productlabel->getNewLabel($_product)){
							?>
								
								<div class="new-label"><span><?php /* @escapeNotVerified */ echo __('New') ?></span></div>
							<?php
							}
							?>
							<div class="product-image-change">
							<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
								  
								    <div class="normal-image">
								   		<?php echo $productImage->toHtml(); ?>
								   </div>
								   <div class="hover-image">
								   <?php echo $producthoverImage->toHtml(); ?>
								   </div>
								   
							</a>
							</div>
							
							
						   
						   <div class="product-item-inner product-hover-inner">
                            <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey')?>
                                            <button type="submit"
                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart primary">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                        <a href="#"
                                           class="action towishlist"
                                           title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                           aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                           data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                           data-action="add-to-wishlist"
                                           role="button">
                                            <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                        </a>
                                    <?php endif; ?>
                                    <?php
                                    $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                    ?>
                                    <a href="#"
                                       class="action tocompare"
                                       title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                       aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                       data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                                       role="button">

                                        <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                    </a>
                                </div>
                            </div>
                            <div class="rating-summary-block">
						    <?php echo $block->getReviewsSummaryHtml($_product, $templateType,true); ?>
						   </div>
                        	</div>
						   
						   <?php /*?><div class="product-grid-image">
							 <div class="product-normal-image">
							 <?php echo $productImage->toHtml(); ?>
							 </div>
							 <div class="product-hover-image">
							 <?php echo $producthoverImage->toHtml(); ?>
							 </div>
						 </div><?php */?>
                    </div>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>
                       
                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
						
                        <?php echo $block->getProductDetailsHtml($_product); ?>

                        
                    </div>
                </div>
                <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>

	<!--<script type="text/javascript">
       require(['jquery','domReady!','themecarousel',], function () {
            jQuery(document).ready(function (){
			
				jQuery(".new-slider.owl-carousel").owlCarousel({
                    items: 5,
                    itemsDesktop: [1080, 4],
                    itemsDesktopSmall: [860, 3],
                    itemsTablet: [768, 3],
                    itemsTabletSmall: [639, 2],
                    itemsMobile: [360, 2],
                    navigation: true
                });
            });
        });
    </script>-->
</div>

<?php }  ?>