<?php
    $order = $block->getOrder();
?>

<?php
    $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $store = $storeManager->getStore();

?>
<div class="checkout-success">
    <?php if($order->getIncrementId()):?>
        <a href="<?php echo $store->getBaseUrl();?>">&nbsp;</a>
    <?php endif;?>
</div>
