<?php 
/**
 * Purpletree_Rma view
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Purpletree License that is bundled with this package in the file license.txt.
 * It is also available through online at this URL: https://www.purpletreesoftware.com/license.html
 *
 * @category    Purpletree
 * @package     Purpletree_Rma
 * @author      Purpletree Software
 * @copyright   Copyright (c) 2017
 * @license     https://www.purpletreesoftware.com/license.html
 */
?>
<?php $orderreturn = $this->getOrderreturn(); ?> 
<div class="purpletree-orderreturn-container">
<div data-role="spinner" class="admin__data-grid-loading-mask" style="display: none; position:fixed;">
        <div class="spinner">
            <span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span>
        </div>
</div>
	<div class="row">
		<div class="col-m-8">
			<div class="purpletree-orderreturn-left">
			<div class="admin__page-section-item-title">
					<span class="title"><?php echo __('Messages') ?></span>
				</div>
				<?php $count =0; ?>
				<?php foreach($this->getMessage() as $message): ?>
				<?php if(!empty($message->getPtsOrderreturnMessage ())): ?>
				<?php $count++; ?>
					<div class="purpletree-orderreturn-box boxx<?php echo $message->getPtsEntityId(); ?> bbx<?php echo $count; ?>">
						<div class="purpletree-orderreturn-msg-box">
							<div class="purpletree-orderreturn-sender">
							
								<strong><span class="capitalizee"><?php echo $message->getPtsMessageSender()==0 ?__('Admin'):__('Customer') ?></span>
								</strong>
								<span><?php echo __('Replied at ') ?><?php echo date('F j, Y G:i A', strtotime($message->getPtsCreatedAt())) ?></span>
							</div>
							<strong>
							<?php if($message->getPtsMessageSender() == 0){ ?>
									
									<?php } else {
									echo $this->getCustomerEmail()['name'].' - '. $this->getCustomerEmail()['email'];
								 } ?>
							</strong>
							<div class="purpletree-orderreturn-desc">
								<?php //echo __('Message') ?> <?php echo $message->getPtsOrderreturnMessage() ?>
							</div>
							<div class="purpletree-orderreturn-file">
							<?php if($message->getPtsOrderreturnMessageAttachment()): ?>
								<strong><?php echo __('Attachment') ?></strong>
								<a href="<?php echo $this->getBaseUrl().'pub/media/purpletree/rma/messages/file'.$message->getPtsOrderreturnMessageAttachment(); ?>" download="<?php echo $message->getPtsOrderreturnMessageAttachment(); ?>"><?php echo __('Download File') ?></a>
							<?php endif; ?>
							</div>
						</div>
					</div>
				<?php endif; ?>
				<?php endforeach; ?>
			</div>
			<div class="reply-form">
				<form action="<?php echo $this->getUrl('*/*/SaveMessage') ?>" name="reply_orderreturn" id="reply_orderreturn"  method="post" enctype="multipart/form-data">
				<?php echo $this->getBlockHtml('formkey')?>
				<input type="hidden" name="pts_orderreturn_id" value="<?php echo $orderreturn->getPtsOrderreturnId(); ?>"/>
				<div class="purpletree-orderreturn-ms">
					<p><strong><?php echo __('Add Message') ?></strong> </p>
					<p><textarea id="pts_orderreturn_message" rows="6" cols="100" name="pts_orderreturn_message"></textarea>
					</p>
					<br/>
					<div class="admin__field-control orderreturnattachment control">
						<input id="pts_orderreturn_message_attachment" name="pts_orderreturn_message_attachment" title="Attach file" class="input-file" type="file"/>   
						<p><?php echo __('Note - File types allowed are pdf, doc, docx, xls, xlsx, csv, txt, jpg, jpeg, png, gif') ?> </p>
					</div>
					<br/>
					<button id="savedata" title="Submit" type="submit" class="scalable "><span><span><span><?php echo __('Submit') ?></span></span></span></button>
				</div>
				</form>
			</div>
		</div>
		<div class="col-m-4">
			<div class="purpletree-orderreturn-right">
				<div class="admin__page-section-item-title">
					<div class="title"><?php echo __('Order Return Information') ?></div>
				</div>
				<form name="save_changes" id="save_changes" method="post" enctype="multipart/form-data">
				 <?php echo $this->getBlockHtml('formkey')?>
				 <input type="hidden" name="pts_orderreturn_id" value="<?php echo $orderreturn->getPtsOrderreturnId(); ?>"/>
				 <div class="pts-return-status">
					 <div class="purpletree-orderreturn-status pts-return-status-<?php echo $orderreturn->getPtsStatusId(); ?>"><?php echo $this->getOrderreturnStatus($orderreturn->getPtsStatusId()); ?>
					 </div>
				 </div>
				<div class="purpletree-orderreturn-msg-box">
					<div class="row margibotomm">
							<div class="col-m-6">
								<strong><?php echo __('Created at: ') ?></strong>
							</div> 
							<div class="col-m-6">
								<?php echo date('F j, Y G:i A', strtotime($orderreturn->getPtsCreatedAt())) ?>
							</div> 
					</div> 
					<div class="row margibotomm">
						<div class="col-m-6">
							<strong>
									<?php echo __('Order ID: ') ?>
							</strong>
						</div> 
						<div class="col-m-6">
						<a href="<?php echo $this->getUrl('sales/order/view',['order_id' => $this->getOrderidfromIncrementId()->getId()]); ?>">
							<?php echo '#'.$orderreturn->getPtsOrderId() ?>
							</a>
						</div>
					</div>
					<div class="row margibotomm">
						<div class="col-m-6">
							<strong><?php echo __('Order Status: ') ?></strong>
						</div> 
						<div class="col-m-6 purpletree-orderreturn-status-label">
							<?php echo $this->getOrder()->getStatusLabel(); ?>
						</div>
					</div>
					
					<div class="row">
						<div class="col-m-6">
							<strong><?php echo __('Request Status: ') ?></strong> 
						</div> 
						<div class="col-m-6">
							 <select name="pts_status_id">
							 <?php   foreach($this->listStatus() as $sstatus) { ?>
							 <?php //if($sstatus['value'] != 2 && $sstatus['value'] != 3) { ?>
								<option <?php if($sstatus['value'] == $orderreturn->getPtsStatusId()){ ?> selected=selected <?php } ?> value="<?php echo $sstatus['value'] ?>"><?php echo $sstatus['label']; ?></option>
							 <?php    } ?>
							 </select> <p></p>
						</div>
					</div> 
					<div class="row">
						<div class="col-m-6">
							<strong><?php echo __('Resolution: ') ?></strong> 
						</div> 
						<div class="col-m-6">
							<select name="pts_resolution_id">
								 <?php  foreach($this->listresolutions() as $rResolution) { ?>
								 <option <?php if($rResolution['value'] == $orderreturn->getPtsResolutionId()){ ?> selected <?php } ?> value="<?php echo $rResolution['value'] ?>"><?php echo $rResolution['label']; ?></option>
								 <?php } ?>
							 </select> <p></p>
						</div>
					</div> 
					<div class="row">
						<div class="col-m-6">
							<strong><?php echo __('Reason: ') ?></strong> 
						</div> 
						<div class="col-m-6">
							<select name="pts_reason_id">
								 <?php  foreach($this->listReasons() as $rReason) { ?>
								 <option <?php if($rReason['value'] == $orderreturn->getPtsReasonId()){ ?> selected <?php } ?> value="<?php echo $rReason['value'] ?>"><?php echo $rReason['label']; ?></option>
								 <?php } ?>
							 </select> <p></p>
						</div> 
					</div> 
					<div class="row">
						<div class="col-m-6">
							<strong><?php echo __('Package Condition: ') ?></strong> 
						</div> 
						<div class="col-m-6">
							<select name="pts_packagecondition_id">
								 <?php  foreach($this->listpackageconditions() as $rrPackageCondition) { ?>
								 <option <?php if($rrPackageCondition['value'] == $orderreturn->getPtsPackageconditionId()){ ?> selected <?php } ?> value="<?php echo $rrPackageCondition['value'] ?>"><?php echo $rrPackageCondition['label']; ?></option>
								 <?php } ?>
							 </select> <p></p>
						</div>
					</div>
					<button id="status_change" title="Save" type="button" class="scalable"><span><span><span><?php echo __('Save') ?></span></span></span></button>
				</div>
				</form>
			</div>
		</div>
	</div>
		<div class="row">
			<div class="col-m-12">
				<!--Prducts-->
<?php if(!empty($this->getProducts())) { ?>
<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php echo __('Items Returned') ?></span>
    </div>
    <div class="admin__table-wrapper">
    <table class="data-table admin__table-primary edit-order-table">
        <thead>
            <tr class="headings">
				<th class="col-product"><span><?php echo __('Product') ?></span></th>
				<th class="col-status"><span><?php echo __('Item Status') ?></span></th>
				<th class="col-price-original"><span><?php echo __('Original Price') ?></span></th>
				<th class="col-price"><span><?php echo __('Price') ?></span></th>
				<th class="col-ordered-qty"><span><?php echo __('Qty') ?></span></th>
				<th class="col-subtotal"><span><?php echo __('Subtotal') ?></span></th>
				<th class="col-tax-amount"><span><?php echo __('Tax Amount') ?></span></th>
				<th class="col-tax-percent"><span><?php echo __('Tax Percent') ?></span></th>
				<th class="col-discont"><span><?php echo __('Discount') ?></span></th>
				<th class="col-total last"><span><?php echo __('Row Total') ?></span></th>
            </tr>
        </thead>
		<?php foreach($this->getProducts() as $item) { ?>
		<?php  
		$order = $this->getOrderidfromIncrementId();
		foreach($order->getAllVisibleItems() as $itema){
			if($itema->getProductId() == $item['pts_product_id']){
				 $getproductfromOrder = $itema;
			}
		} 
		?>
        <tbody class="even">
            <tr>
                <td class="col-product">
					<div id="order_item_32">
						<div id="order_item_32_title" class="product-title"> <?php echo $getproductfromOrder->getName(); ?></div>
							<div class="product-sku-block">
							<span><?php echo __('SKU') ?>:</span><?php echo $getproductfromOrder->getSku(); ?></div>
							<?php 
							 $options = $getproductfromOrder->getProductOptions();
							if(is_array($options) && isset($options['attributes_info']) && !empty($options['attributes_info'])):  ?>
								<dl class="item-options">
								<?php foreach($options['attributes_info'] as $attribs): ?>
									<dt><?php echo $attribs['label'] ?></dt>
									<dd><?php echo $attribs['value'] ?></dd>
									<?php endforeach; ?>
								</dl>
								<?php endif; ?>
					</div>
				</td>
                    <td class="col-status"><?php echo __('Shipped') ?></td>
                    <td class="col-price-original"><span class="price"><?php echo $this->convertToCurrency($getproductfromOrder->getOriginalPrice()); ?></span></td>
                    <td class="col-price">
						<div class="price-excl-tax">
							<span class="price"><?php echo $this->convertToCurrency($getproductfromOrder->getPrice()); ?></span>
						</div>
					</td>
                    <td class="col-ordered-qty">
						<table class="qty-table">
							<tbody>
								<tr>
									<th><?php echo __('Ordered') ?></th>
									<td><?php echo round($getproductfromOrder->getQtyOrdered());?></td>
								</tr>
								<tr>
									<th><?php echo __('Invoiced') ?></th>
									<td><?php echo round($getproductfromOrder->getQtyInvoiced());?></td>
								</tr>
								<tr>
									<th><?php echo __('Shipped') ?></th>
									<td><?php echo round($getproductfromOrder->getQtyShipped());?></td>
								</tr>
							</tbody>
						</table>
					</td>
                    <td class="col-subtotal">
						<div class="price-excl-tax">
							<span class="price"><?php echo $this->convertToCurrency($getproductfromOrder->getPrice()); ?></span>
						</div>
					</td>
                    <td class="col-tax-amount"><span class="price"><?php echo $this->convertToCurrency($getproductfromOrder->getTaxAmount()); ?></span></td>
                    <td class="col-tax-percent"><?php echo $getproductfromOrder->getTaxPercent(); ?>%</td>
                    <td class="col-discount"><span class="price"><?php echo $this->convertToCurrency($getproductfromOrder->getDiscountAmount()); ?></span></td>
                    <td class="col-total last">
						<span class="price"><?php echo $this->convertToCurrency($getproductfromOrder->getRowTotalInclTax()); ?></span>
					</td>
			</tr>
        </tbody>   
		<?php } ?>		
    </table>
</div>
</section>
<?php } ?>
	<!--Prducts-->
			</div>
		</div>
</div>
<script type="text/javascript">
require(['jquery'], function($) {

	$(document).ready(function($) {

		//status change
		$("#savedata").click(function() {
			$('.admin__data-grid-loading-mask').css('display','block');
		});
		$("#returnreceived").click(function() {
			$('.admin__data-grid-loading-mask').css('display','block');
		});
		$("#returncompleted").click(function() {
			$('.admin__data-grid-loading-mask').css('display','block');
		});
		$("#status_change").click(function() {
			
			$('.admin__data-grid-loading-mask').css('display','block');
			var data = new FormData(document.getElementById('save_changes'));
			jQuery.ajax({
			url:"<?php echo $this->getUrl('*/*/saveajax') ?>",
			type:'POST',
				data: data,
				async: false,
				cache: false,
				processData: false,
				contentType: false,
				success: function(response)
				{
				
					$('#messages').remove();
					$('.page-main-actions').after('<div id="messages"><div class="messages"></div></div>');
					$('html').animate({scrollTop:0}, 'slow');//IE, FF
					$('body').animate({scrollTop:0}, 'slow');//chrome, don't know if Safari works
					$('.admin__data-grid-loading-mask').css('display','none');
					if(response.success == true){
						if(response.statuslabel != 0) {
						$('.purpletree-orderreturn-status-label').text(response.statuslabel);
						$('.purpletree-orderreturn-status').text(response.status);
						$('.pts-return-status .purpletree-orderreturn-status').removeAttr('class');
						$('.pts-return-status div').addClass('purpletree-orderreturn-status');
						$('.pts-return-status div').addClass('pts-return-status-'+response.statusid);
						/* if(response.statusid == 2){
							$('.pts-mark-3').css('display','block');
							$('.pts-mark-2').css('display','none');
						} else { 
							if(response.statusid == 3){
								$('.pts-mark').css('display','none');
								$('.pts-credit-memo').css('display','block');
							} else {
								$('.pts-mark').css('display','block');
								$('.pts-credit-memo').css('display','none');
							}
						} */
						$('#messages > .messages').append('<div class="message message-success success"><div data-ui-id="messages-message-success">'+response.messages  +'</div></div>');
					}
					}
					if(response.error == true){
						$('#messages > .messages').append('<div class="message message-error error"><div data-ui-id="messages-message-error">'+response.messageserror  +'</div></div>');
					}	
				}
			});
	});
});
});
</script>

<script type="text/javascript">
require(['jquery','mage/adminhtml/wysiwyg/tiny_mce/setup'], function(jQuery) {
	jQuery(document).ready(function(jQuery) {
	tinyMCE.init({
    mode : "exact",
    elements: "pts_orderreturn_message",
    theme : "advanced",
    plugins : "inlinepopups,style,layer,table,save,advhr,advlink,emotions,iespell,insertdatetime,preview,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras",
    theme_advanced_buttons1 : "newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
    theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,|,undo,redo,|,link,unlink,anchor,cleanup,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
    theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,advhr,|,print,|,ltr,rtl,|,fullscreen",
    theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,|,visualchars,nonbreaking",
    theme_advanced_toolbar_location : "top",
    theme_advanced_toolbar_align : "left",
    theme_advanced_path_location : "bottom",
    extended_valid_elements : "a[name|href|target|title|onclick],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name],hr[class|width|size|noshade],font[face|size|color|style],span[class|align|style]",
    theme_advanced_resize_horizontal : 'true',
    theme_advanced_resizing : 'true',
    apply_source_formatting : 'true',
    convert_urls : 'false',
    force_br_newlines : 'true',
    doctype : '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">'
  });
});
});
</script>