<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="newsletter theme-newsletter">
    <div class="newsletter-static newsletter-top">
	<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('newsletter_text_top')->toHtml();?>
	</div>
	<div class="content">
        <form class="form subscribe"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="field newsletter">

                <div class="control">
                    <input name="email" type="email" id="newsletter"
                                placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>"
                                data-validate="{required:true, 'validate-email':true}"/>
				<button class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
                    <span><?php /* @escapeNotVerified */ echo __('Subscribe') ?></span>
                </button>
                </div>
            </div>

        </form>
    </div>
	 <div class="newsletter-static newsletter-bottom">
		<?php  echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('newsletter_text_bottom')->toHtml();?>
	</div>
</div>
